language: python
install: "pip install -r requirements-dev.txt"
script:
  - nodeenv -p -n 6.10.3
  - npm install serverless@1.26.1 -g
  - cd serverless-youtube-podcasts/
  - npm install --save
  - sls requirements install
  - sls package