language: python
install: "pip install -r requirements.txt"
script:
  - nodeenv -p -n 6.10.2
  - npm install serverless@1.12.1 -g
  - cd serverless-youtube-podcasts/ && npm install --save
  - cd serverless-youtube-podcasts/ && sls requirements install
  - cd serverless-youtube-podcasts/ && sls package